version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn mlapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app                       # Mount project folder
      - static_volume:/app/static     # Mount static volume to match STATIC_ROOT
    expose:
      - "8000"

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - static_volume:/static          # Mount static volume to /static (matches nginx.conf alias)
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount config file
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
